#!/usr/bin/env python

import sys

try:
    with open('.env') as f:
        lines = [line.strip() for line in f.readlines()]
except IOError:
    sys.exit(1)

lines = [
    line for line in lines
    if line and not line.startswith('#')
]
print(' '.join('-e {}'.format(line) for line in lines))
