#!/usr/bin/env python

import sys
import os


def componentize(path):
    pieces = path.split('/')
    for i in range(len(pieces) + 1):
        piece = '/'.join(pieces[0:i])
        if piece:
            yield piece + '/__init__.py'

args = sys.argv[1:]

for arg in args:
    os.makedirs(arg)
    for component in componentize(arg):
        open(component, 'a').close()
