#!/bin/bash

set -e

PORT=8000

while getopts "p:" Option; do
    case $Option in
        p ) PORT=${OPTARG};;
        * ) echo "Unimplemented option chosen."; exit 1;;   # Default.
    esac
done

shift $(($OPTIND - 1))

python -m SimpleHTTPServer $PORT $@
